config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :houses
  resources :buildings
  resources :complaint_details
  resources :tenant_details
  resources :payment_details
  resources :house_details
  resources :caretakers
  get 'users/index'
  resources :admins
  resources :posts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roles
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'admin/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caretaker.rb
class Caretaker < ApplicationRecord
  belongs_to :house
end

app/models/complaint_detail.rb
class ComplaintDetail < ApplicationRecord
    belongs_to :tenant_id
end

app/models/house.rb
class House < ApplicationRecord
    has_many :caretakers
    has_many :tenants                                      
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
    has_one_attached :image, :dependent => :destroy
    belongs_to :tenant_id

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :user_id
  belongs_to :house_id
  has_many :payment_details
  has_many :complaint_details
end

app/models/tenant_detail.rb
class TenantDetail < ApplicationRecord
    belongs_to :users, foreign_key: 'user_id', primary_key: 'id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tenants
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:building_no, :no_of_rooms, :no_of_tenants, :location, :monthly_rent, :space_available, :balcony_availabe, :parking_space)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caretakers_helper.rb
module CaretakersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :building_no %>
    <%= form.text_field :building_no, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :no_of_rooms %>
    <%= form.number_field :no_of_rooms, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :no_of_tenants %>
    <%= form.number_field :no_of_tenants, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :monthly_rent %>
    <%= form.text_field :monthly_rent, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :space_available %>
    <%= form.number_field :space_available, class:"form-control col-6" %>
  </div>

  <div class="field">
    <%= form.label :balcony_availabe %>
    <%= form.check_box :balcony_availabe, class:"form-check-label" %>
  </div>

  <div class="field">
    <%= form.label :parking_space %>
    <%= form.check_box :parking_space, class:"form-check-label" %>
  </div>
  <br>
  <input type="submit" class="btn btn-primary" value="Submit">

<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<%= render 'admins/index' %>
<br>
<div class="card">
<div class="card-body">
  <h1>House Details</h1>
</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Building no</th>
      <th scope="col">No of rooms</th>
      <th scope="col">No of tenants</th>
      <th scope="col">Location</th>
      <th scope="col">Monthly rent</th>
      <th scope="col">Space available</th>
      <th scope="col">Balcony availabe</th>
      <th scope="col">Parking space</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.building_no %></td>
        <td><%= house.no_of_rooms %></td>
        <td><%= house.no_of_tenants %></td>
        <td><%= house.location %></td>
        <td><%= house.monthly_rent %></td>
        <td><%= house.space_available %></td>
        <td><%= house.balcony_availabe %></td>
        <td><%= house.parking_space %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path, class:"btn btn-primary" %>
<%= render 'admins/index_footer' %>

app/views/houses/new.html.erb
<%= render 'admins/index' %>
<p id="notice"><%= notice %></p>

<div class="card">
<div class="card-body">
  <h1>Add New House</h1>
</div>
</div>

<%= render 'form', house: @house %>

<%= render 'admins/index_footer' %>

app/views/houses/show.html.erb
<%= render 'admins/index' %>

<p id="notice"><%= notice %></p>

<form>
<p class="col-sm-4 col-form-label">
  <strong>Building no:</strong>
  <%= @house.building_no %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>No of rooms:</strong>
  <%= @house.no_of_rooms %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>No of tenants:</strong>
  <%= @house.no_of_tenants %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>Monthly rent:</strong>
  <%= @house.monthly_rent %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>Space available:</strong>
  <%= @house.space_available %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>Balcony availabe:</strong>
  <%= @house.balcony_availabe %>
</p>

<p class="col-sm-4 col-form-label">
  <strong>Parking space:</strong>
  <%= @house.parking_space %>
</p>
</form>

<%= link_to 'Edit', edit_house_path(@house), class:"btn btn-secondary btn-large" %>
<%= render 'admins/index_footer' %>