config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :houses
  resources :buildings
  resources :complaint_details
  resources :tenant_details
  resources :payment_details
  resources :house_details
  resources :caretakers
  get 'users/index'
  resources :admins
  resources :posts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roles
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'admin/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caretaker.rb
class Caretaker < ApplicationRecord
  belongs_to :house
end

app/models/complaint_detail.rb
class ComplaintDetail < ApplicationRecord
    belongs_to :tenant_id
end

app/models/house.rb
class House < ApplicationRecord
    has_many :caretakers
    has_many :tenants                                      
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
    has_one_attached :image, :dependent => :destroy
    belongs_to :tenant_id

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :user_id
  belongs_to :house_id
  has_many :payment_details
  has_many :complaint_details
end

app/models/tenant_detail.rb
class TenantDetail < ApplicationRecord
    belongs_to :users, foreign_key: 'user_id', primary_key: 'id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tenants
end

app/controllers/caretakers_controller.rb
class CaretakersController < ApplicationController
  before_action :set_caretaker, only: %i[ show edit update destroy ]

  # GET /caretakers or /caretakers.json
  def index
    @caretakers = Caretaker.all
    # @caretakers = Caretaker.includes(:house).all
    # @detail = @caretakers.houses
    # @caretakers = Caretaker.joins(:house).where(houses: { id: 1 })
  end

  # GET /caretakers/1 or /caretakers/1.json
  def show
  end

  # GET /caretakers/new
  def new
    @caretaker = Caretaker.new
    @house_options = House.all

  end

  # GET /caretakers/1/edit
  def edit
  end

  # POST /caretakers or /caretakers.json
  def create
    @caretaker = Caretaker.new(caretaker_params)

    respond_to do |format|
      if @caretaker.save
        format.html { redirect_to @caretaker, notice: "Caretaker was successfully created." }
        format.json { render :show, status: :created, location: @caretaker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caretakers/1 or /caretakers/1.json
  def update
    respond_to do |format|
      if @caretaker.update(caretaker_params)
        format.html { redirect_to @caretaker, notice: "Caretaker was successfully updated." }
        format.json { render :show, status: :ok, location: @caretaker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caretakers/1 or /caretakers/1.json
  def destroy
    @caretaker.destroy
    respond_to do |format|
      format.html { redirect_to caretakers_url, notice: "Caretaker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caretaker
      @caretaker = Caretaker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caretaker_params
      params.require(:caretaker).permit(:name, :contact_no, :house_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caretakers_helper.rb
module CaretakersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/caretakers/_form.html.erb
<%= form_with(model: caretaker) do |form| %>
  <% if caretaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caretaker.errors.count, "error") %> prohibited this caretaker from being saved:</h2>

      <ul>
        <% caretaker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :contact_no %>
    <%= form.number_field :contact_no, class:"form-control col-6" %>
  </div>

  <div class="field form-group">
    <%= form.label :house_id %>
    <%= form.collection_select(:house_id, @house_options,:id,:building_no,  { class: 'form-control col-6' }) %>

  </div>

  <input type="submit" class="btn btn-primary" value="Submit">

<% end %>

app/views/caretakers/edit.html.erb
<h1>Editing Caretaker</h1>

<%= render 'form', caretaker: @caretaker %>

<%= link_to 'Show', @caretaker %> |
<%= link_to 'Back', caretakers_path %>

app/views/caretakers/index.html.erb
<%= render 'admins/index' %>

<p id="notice"><%= notice %></p>

<div class="card">
<div class="card-body">
  <h1>Care Takers</h1>
</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Contact no</th>
      <th scope="col">House</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
  <% if @caretakers.empty? %>
  <tr>
  <td colspan="8">No Details Found</td>
  </tr>
 <% end %>

    <% @caretakers.each do |caretaker| %>
      <tr>
        <td><%= caretaker.name %></td>
        <td><%= caretaker.contact_no %></td>
        <td><%= caretaker.house.building_no %></td>
        <td><%= link_to 'Show', caretaker %></td>
        <td><%= link_to 'Edit', edit_caretaker_path(caretaker) %></td>
        <td><%= link_to 'Destroy', caretaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Caretaker', new_caretaker_path, class:"btn btn-primary" %>
<%= render 'admins/index_footer' %>

app/views/caretakers/new.html.erb
<%= render 'admins/index' %>
<p id="notice"><%= notice %></p>

<div class="card">
<div class="card-body">
  <h1>Add New Care Taker</h1>
</div>
</div>
<%= render 'form', caretaker: @caretaker %>

<%= render 'admins/index_footer' %>

app/views/caretakers/show.html.erb
<%= render 'admins/index' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @caretaker.name %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @caretaker.contact_no %>
</p>

<p>
  <strong>House:</strong>
  <%= @caretaker.house_id %>
</p>

<%= link_to 'Edit', edit_caretaker_path(@caretaker), class:"btn btn-secondary btn-large" %>   
<%= render 'admins/index_footer' %>